server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/miaosha?serverTimezone=Asia/Shanghai
        username: root
        password: fx1212
    data:
        redis:
            host: 127.0.0.1:6379
#            password: 6379
            database: 0
            jedis:
                pool:
                    enabled: true
                    max-active: 8
                    min-idle: 0
                    max-idle: 8
