server:
    tomcat:
        accept-count: 100
        max-connections: 8192
        threads:
            min-spare: 100
            max: 300
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/miaosha?serverTimezone=Asia/Shanghai
        username: root
        password: fengxiao1212