
spring:
    profiles:
        active: prod
    data:
        redis:
            host: 127.0.0.1:6379
            password: 6379
            database: 0
            jedis:
                pool:
                    enabled: true
                    max-active: 8
                    min-idle: 0
                    max-idle: 8

ms:
    snowflake:
        center-id: 1
        work-id: 1
